spring:
    profiles:
        active:
            - dev
    h2:
        console:
            enabled: true

springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
        path: /swagger-ui.html
        disable-swagger-default-url: true
        display-query-params-without-oauth2: true
